### ISSUE TITLE
dmg password not working for Parallel Desktop

### ISSUE THREAD

**Issue by woodstock789** [Rhinocros/m-gitalk#2]
can't use universal password. it kept asking to try again.

**Comment by Rhinocros** [comment]
what's that filename

**Comment by woodstock789** [comment]
Parallels_Desktop_16.1.2-49151_Crked_-_Digit77.com.dmg

**Comment by Rhinocros** [comment]
digit77.com

**Comment by woodstock789** [comment]
Thank you!
